// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbqV4Wuq1t23tvfMMqYL8-m4YUqeW7pjM',
    appId: '1:646828750230:web:0027b6374652f96fb199b7',
    messagingSenderId: '646828750230',
    projectId: 'spukify-app',
    authDomain: 'spukify-app.firebaseapp.com',
    storageBucket: 'spukify-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8a4wXSwaRDHXd4ZjHamUWThCcAJU-FQE',
    appId: '1:646828750230:android:cc225034326c51fcb199b7',
    messagingSenderId: '646828750230',
    projectId: 'spukify-app',
    storageBucket: 'spukify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXfRd_GkeHS0tnXYiRwDuP5LT5T8cU00',
    appId: '1:646828750230:ios:0841ccad1ba7649ab199b7',
    messagingSenderId: '646828750230',
    projectId: 'spukify-app',
    storageBucket: 'spukify-app.appspot.com',
    iosBundleId: 'com.example.spukify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWXfRd_GkeHS0tnXYiRwDuP5LT5T8cU00',
    appId: '1:646828750230:ios:0841ccad1ba7649ab199b7',
    messagingSenderId: '646828750230',
    projectId: 'spukify-app',
    storageBucket: 'spukify-app.appspot.com',
    iosBundleId: 'com.example.spukify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbqV4Wuq1t23tvfMMqYL8-m4YUqeW7pjM',
    appId: '1:646828750230:web:41cc171a2571fd0db199b7',
    messagingSenderId: '646828750230',
    projectId: 'spukify-app',
    authDomain: 'spukify-app.firebaseapp.com',
    storageBucket: 'spukify-app.appspot.com',
  );
}
